# Generated by Django 4.0.6 on 2022-08-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('isRead', models.IntegerField()),
                ('sender', models.CharField(max_length=50)),
            ],
        ),
    ]
