# Generated by Django 4.0.6 on 2022-08-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('checkTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('docName', models.CharField(max_length=20)),
                ('fatherURL', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('proName', models.CharField(max_length=20)),
                ('groupID', models.IntegerField()),
                ('isDelete', models.IntegerField()),
                ('deleteTime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField()),
                ('isShare', models.IntegerField()),
                ('shareCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('protoName', models.CharField(max_length=20)),
                ('projectID', models.IntegerField()),
                ('canvasData', models.TextField()),
                ('canvasStyle', models.TextField()),
                ('canvasHeight', models.IntegerField()),
                ('canvasWidth', models.IntegerField()),
                ('createTime', models.DateTimeField()),
            ],
        ),
    ]
